FROM oven/bun:1

WORKDIR /workspace

ARG API_URL
ENV VITE_API_URL=${API_URL}

COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["bun", "run", "dev", "--host", "0.0.0.0", "--force"]
