frontend_controllers:
    resource:
        path: ../src/Frontend/Controller/
        namespace: App\Frontend\Controller
    type: attribute



github_connect:
    path: /connect/github
    controller: App\Security\Controller\GithubAuthController::connect

github_check:
    path: /connect/github/check
